server:
  http_listen_port: 9009
  grpc_listen_port: 9095

multitenancy_enabled: false

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data/storage_filesytem

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

distributor:
  ring:
    kvstore:
      store: memberlist
  pool:
    health_check_ingesters: true

ingester:
  ring:
    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512

    kvstore:
      store: inmemory
    replication_factor: 1

limits:
  max_label_names_per_series: 100
