services:
  alloy:
    image: grafana/alloy:v1.6.1
    command:
      - run
      - /etc/alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    depends_on:
      - loki
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      default:
      docker-monitoring_public:
          aliases:
            - docker-monitoring-collector
    restart: unless-stopped
    volumes:
      - ./config/alloy:/etc/alloy
      - alloy:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock

  docker-exporter:
    image: blackprism/docker-exporter:1.4
    command:
      - --docker-compose-only
      - --volume
      - --volume-computation-limit=5000
      - --child-process
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro

  grafana:
    image: grafana/grafana:11.5.2
    env_file:
      - .env
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "enableNativeHTTPHistogram"
      GF_INSTALL_PLUGINS: https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app,grafana-pyroscope-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana

  loki:
    image: grafana/loki:3.4
    command: -config.file=/etc/loki/config.yaml --pattern-ingester.enabled=true
    restart: unless-stopped
    user: root
    volumes:
      - ./config/loki/config.yaml:/etc/loki/config.yaml
      - loki:/data

  prometheus:
    image: prom/prometheus:v3.1.0
    command: --web.enable-remote-write-receiver --enable-feature=native-histograms --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus:/prometheus

  pyroscope:
    image: grafana/pyroscope:1.12.0
    networks:
      - default
      - docker-monitoring_public
    restart: unless-stopped

  tempo:
    image: grafana/tempo:2.7.1
    command: -config.file=/etc/tempo.yaml
    restart: unless-stopped
    volumes:
      - ./config/tempo/config.yaml:/etc/tempo.yaml
      - tempo:/var/tempo

networks:
  docker-monitoring_public:
    external: true

volumes:
  alloy: {}
  grafana: {}
  loki: {}
  tempo: {}
  prometheus: {}
