scrape_configs:
  - job_name: "docker_exporter"
    scrape_interval: 10s
    scrape_timeout: 9s

    static_configs:
      - targets: ["docker-monitoring-docker-exporter-1.docker-monitoring_default:9100"]

scrape_config_files:
  - external_service/*.yml
