apiVersion: 4

datasources:
    - name: loki
      uid: loki
      type: loki
      typeName: Loki
      url: 'http://loki:3100'
      basicAuth: false
      isDefault: false
      readOnly: true
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"trace_id":"(\w+)"'
            name: trace_id
            url: '$${__value.raw}'
            urlDisplayLabel: 'View Trace'
    - name: prometheus
      uid: prometheus
      type: prometheus
      url: 'http://prometheus:9090'
      basicAuth: false
      isDefault: true
    - name: pyroscope
      uid: pyroscope
      type: grafana-pyroscope-datasource
      url: 'http://pyroscope:4040'
    - name: tempo
      uid: tempo
      type: tempo
      url: 'http://tempo:3200'
      jsonData:
        nodeGraph:
          enabled: true
        serviceMap:
          datasourceUid: prometheus
        tracesToLogsV2:
          datasourceUid: loki
          customQuery: true
          query: '{source=~".+"} | json | trace_id = `$${__trace.traceId}`'
          spanEndTimeShift: '1h'
          spanStartTimeShift: '-1h'
        tracesToMetrics:
          datasourceUid: prometheus
        tracesToProfiles:
          datasourceUid: pyroscope
          profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
          tags:
            - key: "service.name"
              value: "service_name"
